### PR TITLE
Revert "Update Readme.md" because russia is bad

### PR DESCRIPTION
**Pull request by OldWorldOrdr**
This reverts commit a127512f13a4a1ba5bdd5fbf368f7d0b6ef8484d.

### CODE REVIEW

**Comment by OldWorldOrdr** [comment]
also u made a minor spelling mistake therefore your opinion is invalid
image

**Comment by catfromplan9** [comment]
hurr durr im so quirky for repeating what literally everyone else says, im so special and unique hurr durr

**Comment by OldWorldOrdr** [comment]
@catfromplan9 https://en.m.wikipedia.org/wiki/War_crimes_in_the_2022_Russian_invasion_of_Ukraine

**Comment by epiccock** [comment]
> @catfromplan9 https://en.wikipedia.org/wiki/War_crimes_in_the_2022_Russian_invasion_of_Ukraine

deserved lol

**Comment by epiccock** [comment]
> also u made a minor spelling mistake therefore your opinion is invalid image

you also made a minor spelling mistake BTW
you said "u" instead of "you"

**Comment by OldWorldOrdr** [comment]
> > @catfromplan9 https://en.wikipedia.org/wiki/War_crimes_in_the_2022_Russian_invasion_of_Ukraine
> 
> deserved lol

they bombed civilians how is that deserved they litterally did nothing.

**Comment by catfromplan9** [comment]
> > > @catfromplan9 https://en.wikipedia.org/wiki/War_crimes_in_the_2022_Russian_invasion_of_Ukraine
> > 
> > 
> > deserved lol
> 
> they bombed civilians how is that deserved they litterally did nothing. also the whole point of a war crime is that NOBODY deserves it no matter how evil they are

You seem to be confused - Ukranians are not human, much more closely related to pigs 🐖

**Comment by democraz20** [comment]
i agree :pig_nose:

**Comment by OldWorldOrdr** [comment]
> political bloat has no place in FOSS

Can someone actually define what politics means, because most of the time when someone complains about stuff being ruined by politics, what they mean by politics is any opinion that disagrees with them.

Supporting gay people is political, opposing gay people isn't.

Supporting Ukraine is political, but supporting Russia isn't

Stop saying you don't like "politics" when what you really mean is you don't like people who disagree with you.

**Comment by OldWorldOrdr** [comment]
> go cry about it on reddit or /pol/. my fork is stripped of this political cancer because i want software to do its job without carrying irrelevant bloat and propaganda

Translation:  My fork is stripped of other opinions because I cannot handle my beliefs being challenged.

**Comment by OldWorldOrdr** [comment]
> you talk a lot of shit about not handling views being challenged for somebody who opened a PR to change a fork because you didn't like its politics.

i didnt do it because i actually care i did it for a quick laugh

**Comment by OldWorldOrdr** [comment]
also im muting this now cuz its boring

**Comment by catfromplan9** [comment]
> hello based russiaposter, i am suing you all for STEALING my AWESOME and ORIGINAL and OBJECTIVELY SUPERIOR fork sanctioned by GOD HIMSELF https://github.com/nulldg/DiscordChatExporterPlus just kidding, the more troll forks; the better. political bloat has no place in FOSS and forks like this are important for asserting that point. but if you're gonna make a fork, please at least strip Tyrrrz's political cancer from the GUI and CLR, change the update target in `DiscordChatExporter.Gui/Services/UpdateService.cs`, and make an unpozzed release. thank you for fighting the good fight, my dear brother.

ok

**Comment by catfromplan9** [comment]
> Supporting gay people is political, opposing gay people isn't.
> 
> Supporting Ukraine is political, but supporting Russia isn't

hmm
> Supporting gay people is political, opposing gay people isn't.

> Supporting Ukraine is political, but supporting Russia isn't

yeah gay isnt political, ukraine is, but i dont give a shit about what mr discordchatexporter ceo says and i can guarantee you nobody reading his ramblings in his project was convinced to support ukraine by it. if anything the opposite. but as for gay, being against it is a matter of common sense you lustful sodomite

**Comment by catfromplan9** [comment]
> I cannot handle my beliefs being challenged.

t. literally every leftist ever

**Pull request closed without merging**
